### ISSUE TITLE
mozplugin-block.txt vs mozplugin2-block.txt

### ISSUE THREAD

**Issue by lupesko** [mozilla-services/shavar-plugin-blocklist#2]
Why are there two lists? what's the difference and which one will be used to actually block Flash?

**Comment by cpeterso** [comment]
@lupesko: neither of these lists are currently active. We need to fix a few Firefox bugs first. The mozplugin-block.txt list will be the default list. The mozplugin2-block.txt list is a more extensive list that we used for a Firefox Beta experiment.

**Comment by lupesko** [comment]
Thanks @cpeterso.
When are you planning to flip the switch in FF and start blocking SWF objects?

**Comment by cpeterso** [comment]
Soon! Maybe Firefox 50, give or take. You can watch [Firefox bug 1275591](https://bugzilla.mozilla.org/show_bug.cgi?id=1275591) to track the progress.
